<a href="https://colab.research.google.com/github/Tensor-Reloaded/Neural-Networks-Template-2025/blob/main/Lab01/Lab01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python fundamentals

### Data types

In [1]:
a = 5
print(type(a))

<class 'int'>


In [2]:
a = 5.0
print(type(a))

<class 'float'>


In [3]:
a = '5'
print(type(a))

<class 'str'>


In [4]:
a = True
print(type(a))

<class 'bool'>


## Containers

In [5]:
a_list = [1, 2, 2, 3.0, '5']
print(a_list)
print(type(a_list))

[1, 2, 2, 3.0, '5']
<class 'list'>


In [6]:
a_set = set(a_list)
print(a_set)
print(type(a_set))
a_set = {1, 2, 3, 4}
print(a_set)

{1, 2, 3.0, '5'}
<class 'set'>
{1, 2, 3, 4}


In [7]:
a_dict = {
    1: 'unu',
    'doi': 2,
    3.0: a_set
}
print("Keys:\t", list(a_dict.keys()))
print("Values:\t", list(a_dict.values()))
print(a_dict)
print(type(a_dict))

Keys:	 [1, 'doi', 3.0]
Values:	 ['unu', 2, {1, 2, 3, 4}]
{1: 'unu', 'doi': 2, 3.0: {1, 2, 3, 4}}
<class 'dict'>


## Functions

In [8]:
def add_two_values(a, b):
    return a + b

add_two_values(5, 6)

11

In [9]:
def multiply(a: float, b: float) -> float:
    return a * b

multiply(4.0, 5.0)

20.0

In [ ]:
multiply("AB", 2)

# Numpy

Check: https://numpy.org/doc/stable/user/absolute_beginners.html

### Installing 3rd party libraries

In [ ]:
%pip install numpy

In [12]:
%pip install timed-decorator

In [13]:
import numpy as np
from math import sqrt
from timed_decorator.simple_timed import timed

In [14]:
x = np.random.uniform(low=-5.5, high=5.5, size=(50,))
x

array([-5.10684796,  3.55174233, -1.0879247 ,  0.63476826,  1.32473059,
        3.25703386, -2.85759607,  0.56524522, -1.34479975, -1.18308003,
       -2.79498795,  4.98782961, -2.52644197, -3.96437629,  2.05677049,
        0.07322086, -3.19067818, -2.78072025, -0.40282111, -0.59072882,
        4.25927931,  3.96061448,  1.87208983, -0.36896469,  5.1911797 ,
       -1.86794248, -2.08074306,  2.74462889, -3.16308914,  1.40324877,
       -5.36347821, -5.12131823, -0.67281397,  1.47291849,  4.53722535,
       -1.62969957,  0.61056549,  0.49667307,  1.00205239,  0.90775139,
       -4.89681083, -0.04053492, -0.12431702, -4.8661491 , -4.63854123,
       -1.83418378,  2.1425354 , -4.38189965,  3.00139925,  0.08148065])

In [15]:
x > 0

array([False,  True, False,  True,  True,  True, False,  True, False,
       False, False,  True, False, False,  True,  True, False, False,
       False, False,  True,  True,  True, False,  True, False, False,
        True, False,  True, False, False, False,  True,  True, False,
        True,  True,  True,  True, False, False, False, False, False,
       False,  True, False,  True,  True])

In [16]:
x[x > 0]

array([3.55174233, 0.63476826, 1.32473059, 3.25703386, 0.56524522,
       4.98782961, 2.05677049, 0.07322086, 4.25927931, 3.96061448,
       1.87208983, 5.1911797 , 2.74462889, 1.40324877, 1.47291849,
       4.53722535, 0.61056549, 0.49667307, 1.00205239, 0.90775139,
       2.1425354 , 3.00139925, 0.08148065])

In [17]:
list(x)

[-5.106847962197298,
 3.551742327760044,
 -1.08792469839935,
 0.634768264995011,
 1.3247305902427025,
 3.2570338611885266,
 -2.8575960749762905,
 0.5652452159399672,
 -1.344799749870452,
 -1.1830800283398855,
 -2.79498795182796,
 4.987829614683591,
 -2.5264419743016333,
 -3.964376290295806,
 2.0567704922743806,
 0.07322085582956284,
 -3.190678175041735,
 -2.7807202498863095,
 -0.40282111450546143,
 -0.5907288200199101,
 4.2592793126330175,
 3.9606144848080085,
 1.8720898257286906,
 -0.36896468997903487,
 5.191179699783955,
 -1.867942476598663,
 -2.08074305996114,
 2.744628890217495,
 -3.163089137435404,
 1.4032487695967086,
 -5.363478206316041,
 -5.121318231290703,
 -0.6728139659857968,
 1.4729184870822731,
 4.53722534601793,
 -1.6296995703833135,
 0.6105654872148687,
 0.4966730686918286,
 1.002052387743654,
 0.9077513856669057,
 -4.8968108326057935,
 -0.04053492331731068,
 -0.12431701664315664,
 -4.86614909782572,
 -4.638541225091128,
 -1.8341837849962137,
 2.142535403821449,
 -4.3818

## Comparing numpy arrays to python lists

In [18]:
@timed(show_args=True, use_seconds=True)
def normalize_np(x: np.ndarray) -> np.ndarray:
    mean = np.mean(x)
    std = np.std(x)
    return (x - mean) / std

@timed(show_args=True, use_seconds=True)
def normalize_py(x: list) -> list:
    mean = sum(x) / len(x)
    var = sum([(i - mean) ** 2 for i in x]) / len(x)
    std = sqrt(var)
    return [(i - mean) / std for i in x]

x = np.random.uniform(low=-5.5, high=5.5, size=(50000,)).astype(np.float64)
y = list(x)
normalized_x = normalize_np(x)
normalized_y = normalize_py(y)
assert np.allclose(normalized_x, normalized_y)

normalize_np(ndarray(50000,)) -> total time: 0.002838324s
normalize_py(list(float64)[50000]) -> total time: 0.027839752s


#### Python is slower than numpy in general

In [19]:
%%timeit

np.min(x)

32.9 µs ± 2.82 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [20]:
%%timeit

min(y)

2.73 ms ± 416 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [21]:
a = np.random.uniform(low=-5.5, high=5.5, size=(50,)).astype(np.float64)
b = list(a)


In [22]:
%%timeit

np.min(a)

5.44 µs ± 1.64 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [23]:
%%timeit

min(b)

1.66 µs ± 470 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## Inplace operations
Use them when you can safely modify the input

In [24]:
@timed(show_args=True, use_seconds=True)
def normalize_np_(x: np.ndarray) -> np.ndarray:
    mean = np.mean(x)
    std = np.std(x)
    x -= mean
    x /= std
    return x

In [28]:
x = np.random.rand(1000, 20000)

# This creates a copy
y = normalize_np(x)
assert not np.allclose(x, y)

# Inplace operations modify the original array! But they are faster and use less memory.
z = normalize_np_(x)
assert np.array_equal(x, z)

normalize_np(ndarray(1000, 20000)) -> total time: 0.189661978s
normalize_np_(ndarray(1000, 20000)) -> total time: 0.139641280s
